### PR TITLE
Palindrome-Checker-project

### PR DESCRIPTION
**Pull request by fatiabdulahi**
Palindrome-Checker-project.
My Palindrome is made by index.html, styles.css and script.js files including linters config files.

### CODE REVIEW

**Comment by fatiabdulahi** [comment]
@sharifa Rezaie hello dear sharifa .I completed my project please review and shear your openian .thanx

**Comment by fatiabdulahi** [comment]
@Sharifarezaie hello dear sharifa I hope you are doing well I completed my project please review my code and shear your opinian .

**Comment by fatiabdulahi** [comment]
@ahzamir ,hello dear Sir I hope you are doing well .I completed my project kindly review and shear your opinean .thanx

**Comment by Sharifarezaie** [comment]
Hi Fatima jan
Your  project Have  not amige  please  added image !

**Comment by fatiabdulahi** [comment]
@Sharifarezaie Hi dear sharifa thank you for your opinian  I have added dimo amage to my reade me file please riveiew again

**Comment by Sharifarezaie** [comment]
@fatiabdulahi
Ok dear Fatima I think your project have no more issue I approved it.

**Comment by fatiabdulahi** [comment]
@ahzamir hello dear Sir I hope you are doing well .my partner aproved my projecd pleas   review and shear your opinian .thank you

**Review by ahzamir — APPROVED** [review]
### Hi @fatiabdulahi 🙋‍♀️,

> Excellent work! 💯 You have done a great job implementing all the project requirements. 🥳 Your feature is complete! Congratulations!!!🎊

- Although I approved your project still your README.md file has some issues, please have a look on it solve them and then merge your branch.

- **[REQUIRED]** Share your project on this [GROUP](https://www.facebook.com/groups/kick-startdev), add a simple Proud Moment text and a screenshot of your project then besides that add your project link at the end of the text as a GitHub Source code reference and post.

- Share your Project on your LinkedIn account and add a proud moment text on it with a screenshot.

- Well Done great design Implemented. 🎯🎉👍
image

# Status: Approved ✅
There is nothing to say other than to merge your branch. 🎉🎯✅👍😊🥳

WinkThumbsUpGIF (2)

 ## Highlights 🌞

🎉 Great Design Implemented 
✔️ Created a professional Repo (You created a repository with your project name)
✔️ Correct use of Gitflow (You created the development branch and made it your default branch, then created and committed your work on your feature branch)
✔️ Commit messages are meaningful
✔️ Setup the linters correctly (You added the correct linters config into your project according to the language you used on your code)
✔️ No linter errors (All linters checks have been passed 🟢)
✔️ You have followed the Palindrome Checker project task and committed using the command line
✔️ Created the pull request (From your feature branch to the development branch you created a pull request and submitted the pull request link for review)
✔️ Good PR description (You added a meaningful description to your PR about your work and the features you added on this pull request)
✔️Your repo has a professional README.md file
✔️Your code is clean
✔️Your design is impressive and responsive

**Cheers 🥂 and Happy coding!!! 👯 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me @ahzamir in your question so I can receive the notification.**

**Comment by fatiabdulahi** [comment]
Splindid tnx Sir for your amazing comment and opinion. I well Merge.

**Pull request merged**
